import json
M=json.load(open('meta2.json',encoding='utf-8'))
DB=M['db']
parts={}
for k,key,side,part in M['meshes']:
    if k=='m' and part: parts.setdefault(key,set()).add(part)
G={
 'PEC':['pectoralis major|sternocostal part','pectoralis major|clavicular part'],
 'TRI':['triceps brachii'],'BI':['biceps brachii'],
 'QUADV':['vastus lateralis','vastus medialis','vastus intermedius'],
 'HAMS':['biceps femoris|long head','semitendinosus','semimembranosus'],
 'ERECT':['iliocostalis','longissimus'],
 'RHOMB':['rhomboid major','rhomboid minor'],
 'GRIP':['flexor digitorum superficialis','flexor digitorum profundus'],
 'WFLEX':['flexor carpi radialis','flexor carpi ulnaris','palmaris longus'],
 'OBL':['external oblique','internal oblique'],
 'HIPFLEX':['iliacus','psoas major'],
 'GASTRO':['gastrocnemius'],
}
E=[
("Barbell bench press","Chest & shoulders","Barbell","Lower the bar to mid-chest with the shoulder blades pinned back, then press up and slightly back.",
 "pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,deltoid|clavicular part:2,TRI:2,serratus anterior:1,anconeus:1"),
("Incline dumbbell press","Chest & shoulders","Dumbbells","Bench at 30–45°, press the dumbbells up over the upper chest.",
 "pectoralis major|clavicular part:3,deltoid|clavicular part:3,pectoralis major|sternocostal part:2,TRI:2,serratus anterior:1"),
("Push-up","Chest & shoulders","Bodyweight","Body in one straight line, lower the chest between the hands, push the floor away.",
 "pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,deltoid|clavicular part:2,TRI:2,serratus anterior:2,rectus abdominis:1,external oblique:1,transversus abdominis:1"),
("Dips","Chest & shoulders","Parallel bars","Lean slightly forward, lower until the upper arms are about parallel to the floor.",
 "pectoralis major|sternocostal part:3,pectoralis major|abdominal part:3,TRI:3,deltoid|clavicular part:2,pectoralis minor:2,RHOMB:1,latissimus dorsi:1"),
("Cable fly","Chest & shoulders","Cable","Slight bend in the elbows, sweep the hands together in an arc in front of the chest.",
 "pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,pectoralis major|abdominal part:2,deltoid|clavicular part:2,coracobrachialis:2,biceps brachii|short head:1"),
("Overhead press","Chest & shoulders","Barbell","Press from the collarbones to lockout overhead, squeezing glutes and abs to avoid leaning back.",
 "deltoid|clavicular part:3,deltoid|acromial part:2,TRI:2,trapezius|descending part:2,trapezius|ascending part:1,serratus anterior:2,supraspinatus:1,rectus abdominis:1,external oblique:1,gluteus maximus:1,ERECT:1"),
("Lateral raise","Chest & shoulders","Dumbbells","Raise the arms out to the side to shoulder height, leading with the elbows.",
 "deltoid|acromial part:3,supraspinatus:2,trapezius|descending part:2,deltoid|clavicular part:1,deltoid|spinal part:1,serratus anterior:1"),
("Front raise","Chest & shoulders","Dumbbells","Raise straight arms forward to shoulder height.",
 "deltoid|clavicular part:3,pectoralis major|clavicular part:2,deltoid|acromial part:1,serratus anterior:1,trapezius|descending part:1"),
("Pull-up","Back","Bodyweight","Overhand grip, pull the chest toward the bar by driving the elbows down.",
 "latissimus dorsi:3,teres major:2,BI:2,brachialis:2,brachioradialis:2,trapezius|ascending part:2,RHOMB:2,deltoid|spinal part:1,pectoralis major|sternocostal part:1,infraspinatus:1,GRIP:1,rectus abdominis:1"),
("Chin-up","Back","Bodyweight","Underhand grip, pull until the chin clears the bar.",
 "latissimus dorsi:3,BI:3,brachialis:2,teres major:2,pectoralis major|sternocostal part:1,trapezius|ascending part:1,RHOMB:1,GRIP:1"),
("Lat pulldown","Back","Cable","Pull the bar to the upper chest, elbows down and slightly back.",
 "latissimus dorsi:3,teres major:2,BI:2,brachialis:2,trapezius|ascending part:1,RHOMB:1,deltoid|spinal part:1,GRIP:1"),
("Barbell row","Back","Barbell","Hinge to about 45°, pull the bar to the lower ribs.",
 "latissimus dorsi:3,trapezius|transverse part:3,RHOMB:3,deltoid|spinal part:2,teres major:2,BI:2,brachialis:2,ERECT:2,infraspinatus:1,HAMS:1,gluteus maximus:1,GRIP:1"),
("Seated cable row","Back","Cable","Sit tall, pull the handle to the stomach and squeeze the shoulder blades together.",
 "latissimus dorsi:3,RHOMB:3,trapezius|transverse part:2,deltoid|spinal part:2,teres major:2,BI:2,brachialis:2,ERECT:1"),
("Face pull","Back","Cable","Rope at face height, pull toward the forehead while rotating the hands outward.",
 "deltoid|spinal part:3,infraspinatus:3,teres minor:3,trapezius|transverse part:2,RHOMB:2,trapezius|ascending part:1,trapezius|descending part:1,BI:1"),
("Rear-delt fly","Back","Dumbbells","Hinged forward, raise the arms out to the side with soft elbows.",
 "deltoid|spinal part:3,trapezius|transverse part:2,RHOMB:2,infraspinatus:2,teres minor:2"),
("Shrug","Back","Dumbbells","Lift the shoulders straight up toward the ears, pause, lower slowly.",
 "trapezius|descending part:3,levator scapulae:3,GRIP:2,RHOMB:1,trapezius|transverse part:1"),
("Straight-arm pulldown","Back","Cable","Arms straight, sweep the bar from eye level down to the thighs.",
 "latissimus dorsi:3,teres major:3,triceps brachii|long head:2,pectoralis major|abdominal part:1,rectus abdominis:1"),
("Cable external rotation","Back","Cable","Elbow pinned to the side at 90°, rotate the forearm outward.",
 "infraspinatus:3,teres minor:3,deltoid|spinal part:1,supraspinatus:1"),
("Close-grip bench press","Arms","Barbell","Hands shoulder-width, elbows close to the body.",
 "TRI:3,pectoralis major|sternocostal part:2,pectoralis major|clavicular part:2,deltoid|clavicular part:2,anconeus:1"),
("Triceps pushdown","Arms","Cable","Elbows fixed at the sides, extend the arms fully.",
 "triceps brachii|lateral head:3,triceps brachii|medial head:3,triceps brachii|long head:2,anconeus:2"),
("Overhead triceps extension","Arms","Cable or dumbbell","Arms overhead, lower the weight behind the head and extend.",
 "triceps brachii|long head:3,triceps brachii|lateral head:2,triceps brachii|medial head:2,anconeus:1,rectus abdominis:1"),
("Barbell curl","Arms","Barbell","Elbows by the sides, curl the bar to the shoulders without swinging.",
 "BI:3,brachialis:2,brachioradialis:2,deltoid|clavicular part:1,WFLEX:1"),
("Hammer curl","Arms","Dumbbells","Thumbs up, curl the dumbbells to the shoulders.",
 "brachialis:3,brachioradialis:3,BI:2,extensor carpi radialis longus:1"),
("Wrist curl","Arms","Dumbbells","Forearms on the thighs, palms up, curl the wrists up.",
 "flexor carpi radialis:3,flexor carpi ulnaris:3,palmaris longus:2,GRIP:2"),
("Reverse wrist curl","Arms","Dumbbells","Forearms on the thighs, palms down, lift the backs of the hands.",
 "extensor carpi radialis longus:3,extensor carpi radialis brevis:3,extensor carpi ulnaris:3,extensor digitorum:2,brachioradialis:1"),
("Back squat","Legs","Barbell","Bar on the upper back, sit down between the heels to at least parallel, drive up.",
 "QUADV:3,gluteus maximus:3,adductor magnus:2,rectus femoris:2,ERECT:2,multifidus:1,soleus:1,gastrocnemius:1,HAMS:1,gluteus medius:1,rectus abdominis:1,external oblique:1,transversus abdominis:1"),
("Front squat","Legs","Barbell","Bar on the front of the shoulders, elbows high, torso upright.",
 "QUADV:3,rectus femoris:2,gluteus maximus:2,adductor magnus:2,ERECT:2,rectus abdominis:1,transversus abdominis:1,soleus:1"),
("Bulgarian split squat","Legs","Dumbbells","Rear foot on a bench, lower the back knee toward the floor.",
 "QUADV:3,gluteus maximus:3,rectus femoris:2,adductor magnus:2,gluteus medius:2,gluteus minimus:1,HAMS:1,soleus:1,quadratus lumborum:1"),
("Walking lunge","Legs","Dumbbells","Long steps, back knee almost touching the floor.",
 "QUADV:3,gluteus maximus:3,rectus femoris:2,adductor magnus:2,gluteus medius:2,HAMS:1,gastrocnemius:1,soleus:1,quadratus lumborum:1,OBL:1"),
("Leg press","Legs","Machine","Feet shoulder-width on the platform, lower until the knees reach about 90°.",
 "QUADV:3,gluteus maximus:2,adductor magnus:2,rectus femoris:1,gastrocnemius:1"),
("Step-up","Legs","Dumbbells","Step onto a box and drive up through the front heel.",
 "gluteus maximus:3,QUADV:3,gluteus medius:2,rectus femoris:1,adductor magnus:1,soleus:1,gastrocnemius:1"),
("Leg extension","Legs","Machine","Extend the knees fully and pause at the top.",
 "rectus femoris:3,vastus lateralis:3,vastus medialis:3,vastus intermedius:3"),
("Lying leg curl","Legs","Machine","Curl the heels toward the glutes, hips pressed into the pad.",
 "biceps femoris|long head:3,biceps femoris|short head:3,semitendinosus:3,semimembranosus:3,gastrocnemius:2,gracilis:1,sartorius:1,popliteus:1,plantaris:1"),
("Nordic curl","Legs","Bodyweight","Kneel with the ankles anchored, lower the body forward as slowly as possible.",
 "semitendinosus:3,biceps femoris|long head:3,biceps femoris|short head:2,semimembranosus:2,gastrocnemius:2,gluteus maximus:1,ERECT:1,gracilis:1"),
("Standing calf raise","Legs","Machine","Knees straight, rise onto the balls of the feet, full stretch at the bottom.",
 "gastrocnemius:3,soleus:2,fibularis longus:1,tibialis posterior:1,flexor hallucis longus:1,flexor digitorum longus:1"),
("Seated calf raise","Legs","Machine","Knees bent at 90°, rise onto the balls of the feet.",
 "soleus:3,gastrocnemius:1,tibialis posterior:1,fibularis longus:1,flexor hallucis longus:1"),
("Tibialis raise","Legs","Bodyweight","Back against a wall, heels forward, lift the toes toward the shins.",
 "tibialis anterior:3,extensor digitorum longus:2,extensor hallucis longus:2,fibularis tertius:1"),
("Copenhagen plank","Legs","Bench","Side plank with the top leg on a bench, bottom leg lifted.",
 "adductor longus:3,adductor brevis:2,adductor magnus:2,gracilis:2,pectineus:2,OBL:2,gluteus medius:1,quadratus lumborum:1,transversus abdominis:1"),
("Banded side walk","Legs","Resistance band","Band above the knees, half squat, step sideways keeping tension.",
 "gluteus medius:3,gluteus minimus:3,tensor fasciae latae:2,gluteus maximus:2,piriformis:1,quadratus lumborum:1"),
("Romanian deadlift","Hinge","Barbell","Soft knees, push the hips back and lower the bar along the legs until the hamstrings stretch.",
 "HAMS:3,gluteus maximus:3,adductor magnus:2,ERECT:2,multifidus:2,trapezius|descending part:1,latissimus dorsi:1,GRIP:1"),
("Conventional deadlift","Hinge","Barbell","Bar over mid-foot, brace, push the floor away and stand up with the bar close.",
 "gluteus maximus:3,ERECT:3,adductor magnus:2,QUADV:2,HAMS:2,latissimus dorsi:2,trapezius|descending part:2,multifidus:2,quadratus lumborum:2,GRIP:2,RHOMB:1,rectus femoris:1,rectus abdominis:1,OBL:1,transversus abdominis:1,soleus:1"),
("Hip thrust","Hinge","Barbell","Upper back on a bench, drive the hips up until the torso is level, chin tucked.",
 "gluteus maximus:3,gluteus medius:2,HAMS:1,adductor magnus:1,QUADV:1,ERECT:1,gluteus minimus:1"),
("Good morning","Hinge","Barbell","Bar on the upper back, hinge forward with a flat back until the hamstrings stretch.",
 "ERECT:3,HAMS:3,gluteus maximus:2,adductor magnus:2,multifidus:2"),
("Back extension","Hinge","Bench","Hips on the pad, lower the torso and raise it to a straight line.",
 "ERECT:3,multifidus:3,gluteus maximus:2,HAMS:2,quadratus lumborum:1"),
("Kettlebell swing","Hinge","Kettlebell","Hike the bell back between the legs, snap the hips forward to float it to chest height.",
 "gluteus maximus:3,HAMS:2,ERECT:2,adductor magnus:1,deltoid|clavicular part:1,GRIP:1,rectus abdominis:1"),
("Plank","Core","Bodyweight","Forearms under the shoulders, body straight, brace as if expecting a punch.",
 "transversus abdominis:3,rectus abdominis:3,OBL:2,deltoid|clavicular part:1,serratus anterior:1,gluteus maximus:1,rectus femoris:1"),
("Side plank","Core","Bodyweight","Elbow under the shoulder, hips lifted in line with the body.",
 "internal oblique:3,external oblique:3,quadratus lumborum:3,gluteus medius:2,transversus abdominis:2,rectus abdominis:1,deltoid|acromial part:1"),
("Hanging leg raise","Core","Bar","Hang from a bar, curl the pelvis up and raise the legs without swinging.",
 "rectus abdominis:3,HIPFLEX:3,rectus femoris:2,OBL:2,GRIP:2,tensor fasciae latae:1,sartorius:1,latissimus dorsi:1,teres major:1"),
("Ab wheel rollout","Core","Ab wheel","From the knees, roll out as far as you can without the lower back sagging.",
 "rectus abdominis:3,OBL:2,transversus abdominis:2,latissimus dorsi:2,triceps brachii|long head:1,HIPFLEX:1,pectoralis major|sternocostal part:1,serratus anterior:1"),
("Cable crunch","Core","Cable","Kneel, rope by the head, curl the ribs toward the pelvis.",
 "rectus abdominis:3,OBL:2"),
("Pallof press","Core","Cable","Stand side-on to the cable, press the handle straight out and resist rotation.",
 "external oblique:3,internal oblique:3,transversus abdominis:2,rectus abdominis:2,quadratus lumborum:1,gluteus medius:1,multifidus:1"),
("Dead bug","Core","Bodyweight","On the back, lower the opposite arm and leg while keeping the lower back on the floor.",
 "transversus abdominis:3,rectus abdominis:3,OBL:2,HIPFLEX:1"),
("Cable woodchop","Core","Cable","Rotate the torso to pull the handle diagonally across the body, pivoting the back foot.",
 "external oblique:3,internal oblique:3,rectus abdominis:2,transversus abdominis:1,latissimus dorsi:1,gluteus maximus:1,gluteus medius:1"),
("Farmer's carry","Grip & carry","Dumbbells","Walk with heavy weights at the sides, shoulders back, ribs down.",
 "GRIP:3,flexor pollicis longus:2,trapezius|descending part:2,quadratus lumborum:2,OBL:2,gluteus medius:2,levator scapulae:1,ERECT:1,WFLEX:1,gastrocnemius:1,soleus:1,transversus abdominis:1"),
("Dead hang","Grip & carry","Bar","Hang from a bar with straight arms and active shoulders.",
 "GRIP:3,flexor pollicis longus:2,latissimus dorsi:1,teres major:1,flexor carpi ulnaris:1,flexor carpi radialis:1"),
("Weighted neck flexion","Neck","Weight plate","Lying on a bench, head off the end, nod the chin toward the chest.",
 "sternocleidomastoid:3,scalenus anterior:2,longus colli:2,longus capitis:2"),
("Neck extension","Neck","Neck harness","Hinged forward, extend the head back against resistance.",
 "splenius capitis:3,semispinalis:3,trapezius|descending part:2,splenius cervicis:2,levator scapulae:1"),
]

E+=[
("Chest press machine","Chest & shoulders","Machine","Handles at mid-chest height, press forward without letting the shoulders roll forward.",
 "pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,deltoid|clavicular part:2,TRI:2"),
("Dumbbell bench press","Chest & shoulders","Dumbbells","Lower the dumbbells to the sides of the chest, press up and slightly together.",
 "pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,deltoid|clavicular part:2,TRI:2,serratus anterior:1,biceps brachii|short head:1,infraspinatus:1"),
("Incline barbell bench press","Chest & shoulders","Barbell","Bench at 30–45°, lower the bar to the upper chest.",
 "pectoralis major|clavicular part:3,deltoid|clavicular part:3,pectoralis major|sternocostal part:2,TRI:2,serratus anterior:1"),
("Decline bench press","Chest & shoulders","Barbell","Head lower than hips, lower the bar to the lower chest.",
 "pectoralis major|sternocostal part:3,pectoralis major|abdominal part:3,TRI:2,deltoid|clavicular part:1"),
("Pec deck","Chest & shoulders","Machine","Elbows slightly bent on the pads, bring the arms together in front of the chest.",
 "pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,pectoralis major|abdominal part:2,deltoid|clavicular part:1,coracobrachialis:1"),
("Low-to-high cable fly","Chest & shoulders","Cable","Cables low, sweep the hands up and together to eye level.",
 "pectoralis major|clavicular part:3,deltoid|clavicular part:2,pectoralis major|sternocostal part:1,serratus anterior:1,biceps brachii|short head:1"),
("Diamond push-up","Chest & shoulders","Bodyweight","Hands together under the chest forming a diamond, elbows close to the body.",
 "TRI:3,pectoralis major|sternocostal part:2,deltoid|clavicular part:2,anconeus:1,serratus anterior:1,rectus abdominis:1"),
("Shoulder press machine","Chest & shoulders","Machine","Seated, press the handles overhead without arching the back.",
 "deltoid|clavicular part:3,deltoid|acromial part:2,TRI:2,trapezius|descending part:1,serratus anterior:1"),
("Seated dumbbell press","Chest & shoulders","Dumbbells","Back supported, press the dumbbells from ear height to overhead.",
 "deltoid|clavicular part:3,deltoid|acromial part:2,TRI:2,trapezius|descending part:1,serratus anterior:1,supraspinatus:1"),
("Arnold press","Chest & shoulders","Dumbbells","Start palms facing you, rotate the palms forward while pressing overhead.",
 "deltoid|clavicular part:3,deltoid|acromial part:2,TRI:2,pectoralis major|clavicular part:1,serratus anterior:1,trapezius|descending part:1"),
("Landmine press","Chest & shoulders","Barbell","Press the end of a barbell anchored in a corner up and forward.",
 "deltoid|clavicular part:3,pectoralis major|clavicular part:2,TRI:2,serratus anterior:2,OBL:1"),
("Cable lateral raise","Chest & shoulders","Cable","Cable from the opposite side, raise the arm to shoulder height.",
 "deltoid|acromial part:3,supraspinatus:2,trapezius|descending part:1,deltoid|spinal part:1"),
("Upright row","Chest & shoulders","Barbell","Pull the bar up along the body to chest height, elbows leading.",
 "deltoid|acromial part:3,trapezius|descending part:3,deltoid|clavicular part:2,supraspinatus:1,BI:1,brachialis:1"),
("Reverse pec deck","Back","Machine","Face the pad, sweep the arms back in a wide arc.",
 "deltoid|spinal part:3,trapezius|transverse part:2,RHOMB:2,infraspinatus:2,teres minor:1"),
("One-arm dumbbell row","Back","Dumbbells","Hand and knee on a bench, row the dumbbell to the hip.",
 "latissimus dorsi:3,RHOMB:2,trapezius|transverse part:2,teres major:2,deltoid|spinal part:2,BI:2,brachialis:1,OBL:1,GRIP:1"),
("T-bar row","Back","Machine","Chest supported or hinged, pull the handles to the stomach.",
 "latissimus dorsi:3,trapezius|transverse part:3,RHOMB:3,deltoid|spinal part:2,teres major:2,BI:2,brachialis:1,ERECT:1"),
("Machine row","Back","Machine","Chest on the pad, pull the handles back and squeeze the shoulder blades.",
 "latissimus dorsi:3,RHOMB:3,trapezius|transverse part:2,deltoid|spinal part:2,teres major:2,BI:1,brachialis:1"),
("Inverted row","Back","Bodyweight","Hang under a bar with a straight body, pull the chest to the bar.",
 "latissimus dorsi:3,RHOMB:3,trapezius|transverse part:2,deltoid|spinal part:2,BI:2,brachialis:1,gluteus maximus:1,rectus abdominis:1"),
("Assisted pull-up","Back","Machine","Kneel on the assist pad, pull the chest to the handles.",
 "latissimus dorsi:3,teres major:2,BI:2,brachialis:2,trapezius|ascending part:1,RHOMB:1"),
("Dumbbell pullover","Back","Dumbbells","Across a bench, lower the dumbbell behind the head with slightly bent arms and pull it back over the chest.",
 "latissimus dorsi:3,pectoralis major|sternocostal part:2,teres major:2,triceps brachii|long head:2,serratus anterior:1,pectoralis minor:1"),
("Preacher curl","Arms","Machine","Upper arms on the pad, curl without lifting the elbows.",
 "biceps brachii|short head:3,biceps brachii|long head:2,brachialis:3,brachioradialis:1"),
("Incline dumbbell curl","Arms","Dumbbells","Lean back on an incline bench, arms hanging, curl without moving the elbows forward.",
 "biceps brachii|long head:3,biceps brachii|short head:2,brachialis:2,brachioradialis:1"),
("Cable curl","Arms","Cable","Elbows by the sides, curl the handle to the shoulders.",
 "BI:3,brachialis:2,brachioradialis:1,WFLEX:1"),
("Concentration curl","Arms","Dumbbells","Seated, elbow against the inner thigh, curl one dumbbell.",
 "BI:3,brachialis:2,brachioradialis:1"),
("Skull crusher","Arms","Barbell","Lying, lower the bar toward the forehead by bending only the elbows.",
 "triceps brachii|long head:3,triceps brachii|lateral head:3,triceps brachii|medial head:3,anconeus:1"),
("Bench dip","Arms","Bench","Hands on a bench behind you, lower the hips by bending the elbows.",
 "TRI:3,deltoid|clavicular part:2,pectoralis major|sternocostal part:2,anconeus:1"),
("Goblet squat","Legs","Dumbbell or kettlebell","Hold the weight at the chest, squat deep between the knees.",
 "QUADV:3,gluteus maximus:3,adductor magnus:2,rectus femoris:2,ERECT:1,rectus abdominis:1,transversus abdominis:1,soleus:1"),
("Hack squat","Legs","Machine","Back on the pad, feet mid-platform, squat until thighs are below parallel.",
 "QUADV:3,gluteus maximus:2,adductor magnus:2,rectus femoris:1,soleus:1"),
("Smith machine squat","Legs","Machine","Bar on the upper back, feet slightly forward, squat to parallel or below.",
 "QUADV:3,gluteus maximus:3,adductor magnus:2,rectus femoris:1,ERECT:1,soleus:1"),
("Seated leg curl","Legs","Machine","Pad above the heels, curl down and back as far as possible.",
 "semitendinosus:3,semimembranosus:3,biceps femoris|long head:3,biceps femoris|short head:3,gracilis:1,sartorius:1,gastrocnemius:1,popliteus:1"),
("Hip abduction machine","Legs","Machine","Seated, push the pads outward and control the return.",
 "gluteus medius:3,gluteus minimus:3,tensor fasciae latae:3,gluteus maximus:2,piriformis:1,sartorius:1"),
("Hip adduction machine","Legs","Machine","Seated, squeeze the pads together and control the return.",
 "adductor longus:3,adductor brevis:3,adductor magnus:3,gracilis:2,pectineus:2,adductor minimus:2"),
("Cable glute kickback","Legs","Cable","Ankle strap, kick the leg straight back without arching the lower back.",
 "gluteus maximus:3,HAMS:2,gluteus medius:1,ERECT:1"),
("Glute bridge","Hinge","Bodyweight","On the back, knees bent, drive the hips up until the body is in line.",
 "gluteus maximus:3,HAMS:2,gluteus medius:1,ERECT:1,adductor magnus:1"),
("Leg press calf raise","Legs","Machine","Balls of the feet at the bottom of the platform, push through the toes.",
 "gastrocnemius:3,soleus:2,fibularis longus:1,tibialis posterior:1"),
("Reverse lunge","Legs","Dumbbells","Step back, lower the back knee, drive up through the front foot.",
 "gluteus maximus:3,QUADV:3,adductor magnus:2,gluteus medius:2,rectus femoris:1,HAMS:1,soleus:1"),
("Sumo deadlift","Hinge","Barbell","Wide stance, toes out, grip inside the knees, push the knees out and stand up.",
 "gluteus maximus:3,QUADV:3,adductor magnus:3,adductor longus:2,ERECT:2,HAMS:2,trapezius|descending part:1,latissimus dorsi:1,GRIP:2,gluteus medius:1"),
("Trap bar deadlift","Hinge","Trap bar","Stand inside the bar, hips lower than a conventional deadlift, push the floor away.",
 "QUADV:3,gluteus maximus:3,ERECT:2,adductor magnus:2,HAMS:2,trapezius|descending part:2,GRIP:2,latissimus dorsi:1,quadratus lumborum:1"),
("Single-leg Romanian deadlift","Hinge","Dumbbells","Hinge on one leg, the free leg extending behind, hips square.",
 "HAMS:3,gluteus maximus:3,gluteus medius:2,ERECT:2,adductor magnus:2,gluteus minimus:1,OBL:1,fibularis longus:1,tibialis posterior:1"),
("Cable pull-through","Hinge","Cable","Face away from a low cable, rope between the legs, hinge and drive the hips forward.",
 "gluteus maximus:3,HAMS:2,ERECT:1,adductor magnus:1"),
("Glute-ham raise","Hinge","Machine","Lower the torso forward from the knees, then pull back up with the hamstrings.",
 "semitendinosus:3,biceps femoris|long head:3,semimembranosus:3,gastrocnemius:2,gluteus maximus:2,ERECT:1"),
("Power clean","Full body","Barbell","Pull from the floor, extend the hips explosively and catch the bar on the front of the shoulders.",
 "gluteus maximus:3,QUADV:3,HAMS:3,trapezius|descending part:3,ERECT:2,gastrocnemius:2,soleus:2,deltoid|clavicular part:1,deltoid|acromial part:1,BI:1,GRIP:2,adductor magnus:2"),
("Thruster","Full body","Barbell","Front squat, then drive up and press the bar overhead in one motion.",
 "QUADV:3,gluteus maximus:3,deltoid|clavicular part:3,TRI:2,deltoid|acromial part:1,rectus femoris:2,serratus anterior:1,ERECT:1,rectus abdominis:1"),
("Crunch","Core","Bodyweight","Curl the shoulders off the floor, ribs toward the pelvis, lower back stays down.",
 "rectus abdominis:3,OBL:2"),
("Machine crunch","Core","Machine","Seated, curl the torso down against the pads.",
 "rectus abdominis:3,OBL:2,HIPFLEX:1"),
("Sit-up","Core","Bodyweight","From lying, curl all the way up to sitting.",
 "rectus abdominis:3,HIPFLEX:3,rectus femoris:2,OBL:2"),
("Lying leg raise","Core","Bodyweight","On the back, raise straight legs to vertical without the lower back arching.",
 "HIPFLEX:3,rectus abdominis:3,rectus femoris:2,OBL:1,tensor fasciae latae:1,sartorius:1"),
("Russian twist","Core","Weight plate","Seated with the torso leaned back, rotate side to side.",
 "external oblique:3,internal oblique:3,rectus abdominis:2,HIPFLEX:2,transversus abdominis:1"),
("Back extension machine","Hinge","Machine","Seated, extend the torso back against the pad.",
 "ERECT:3,multifidus:3,quadratus lumborum:2,gluteus maximus:1"),
]

E+=[
("Side-lying hip abduction","Legs","Bodyweight","Lie on your side, top leg straight and slightly behind the body, toes pointing forward. Lift without rolling the hips back.",
 "gluteus medius:3,gluteus minimus:3,tensor fasciae latae:2,gluteus maximus:1,quadratus lumborum:1,OBL:1"),
("Clamshell","Legs","Resistance band","Side-lying, hips and knees bent, feet together. Open the top knee without rolling the pelvis back.",
 "gluteus medius:3,gluteus maximus:2,gluteus minimus:2,piriformis:2,obturator internus:1,gemellus superior:1,gemellus inferior:1,tensor fasciae latae:1"),
("Single-leg box squat","Legs","Bodyweight","Stand on one leg in front of a box, sit back to touch it and stand up, knee tracking over the toes.",
 "QUADV:3,gluteus maximus:3,gluteus medius:2,gluteus minimus:2,adductor magnus:1,tensor fasciae latae:1,soleus:1,OBL:1,quadratus lumborum:1"),
("Lateral step-down","Legs","Bodyweight","Stand sideways on a step, slowly lower the free heel to the floor and press back up, pelvis level.",
 "QUADV:3,gluteus medius:2,gluteus maximus:2,gluteus minimus:2,tensor fasciae latae:1,soleus:1"),
("Lateral step-up","Legs","Dumbbells","Stand beside a box, step up sideways and drive through the top leg without pushing off the bottom one.",
 "gluteus maximus:3,gluteus medius:3,QUADV:3,gluteus minimus:2,tensor fasciae latae:1,adductor magnus:1"),
("Standing cable hip abduction","Legs","Cable","Ankle strap on the outer leg, stand tall and sweep the leg out to the side without leaning.",
 "gluteus medius:3,gluteus minimus:3,tensor fasciae latae:2,gluteus maximus:1,quadratus lumborum:1,OBL:1"),
("Side plank with hip abduction","Legs","Bodyweight","Hold a side plank and lift the top leg, keeping it in line with the body.",
 "gluteus medius:3,gluteus minimus:3,external oblique:3,internal oblique:3,quadratus lumborum:3,tensor fasciae latae:2,gluteus maximus:2,transversus abdominis:2"),
]

E+=[
("Reverse hyperextension","Hinge","Machine","Lie face down over the pad, swing the legs up in line with the torso, lower under control without swinging.",
 "gluteus maximus:3,ERECT:2,multifidus:2,HAMS:2,spinalis:2,adductor magnus:1,quadratus lumborum:1"),
("Sissy squat","Legs","Bodyweight","Rise onto the toes, push the knees forward and lean back, lowering in one straight line from knees to shoulders.",
 "QUADV:3,rectus femoris:3,gluteus maximus:1,tibialis anterior:1,soleus:1,gastrocnemius:1,rectus abdominis:1"),
("Jefferson curl","Hinge","Dumbbells","Stand on a box with a light weight and roll the spine down one segment at a time, then reverse slowly.",
 "ERECT:3,multifidus:3,spinalis:2,interspinales:2,HAMS:2,gluteus maximus:2,adductor magnus:1,rotatores:1,intertransversarii:1,GRIP:1"),
("Wrist roller","Arms","Wrist roller","Arms extended, roll the weight up by alternating wrist flexion and extension, then lower it the same way.",
 "WFLEX:3,extensor carpi radialis longus:3,extensor carpi radialis brevis:3,extensor carpi ulnaris:3,extensor digitorum:2,GRIP:2,brachioradialis:2,deltoid|clavicular part:2,deltoid|acromial part:1,flexor pollicis longus:1"),
("Hip airplane","Legs","Bodyweight","Hinge on one leg and rotate the pelvis open and closed over the planted foot without the knee collapsing.",
 "gluteus medius:3,gluteus minimus:3,gluteus maximus:2,piriformis:2,obturator internus:2,obturator externus:2,gemellus superior:2,gemellus inferior:2,quadratus femoris:2,HAMS:2,tensor fasciae latae:1,adductor magnus:1,fibularis longus:1,tibialis posterior:1,OBL:1"),
("Zercher squat","Legs","Barbell","Hold the bar in the crooks of the elbows against the stomach and squat deep with an upright torso.",
 "QUADV:3,gluteus maximus:3,adductor magnus:2,ERECT:2,rectus femoris:2,BI:1,brachialis:1,rectus abdominis:1,transversus abdominis:1,trapezius|descending part:1,soleus:1"),
("Bird dog","Core","Bodyweight","On hands and knees, extend the opposite arm and leg together without letting the pelvis rotate.",
 "multifidus:3,ERECT:2,spinalis:2,rotatores:2,gluteus maximus:2,OBL:2,transversus abdominis:2,deltoid|clavicular part:1,HAMS:1,gluteus medius:1,quadratus lumborum:1,serratus anterior:1,rectus abdominis:1"),
("Prone Y-T-W raise","Back","Dumbbells","Chest on an incline bench with light weights, raise the arms in a Y, with thumbs up, leading with the shoulder blades.",
 "trapezius|ascending part:3,trapezius|transverse part:2,deltoid|spinal part:2,deltoid|acromial part:2,infraspinatus:1,teres minor:1,supraspinatus:1,serratus anterior:1,RHOMB:1,ERECT:1"),
("Cuban press","Chest & shoulders","Dumbbells","Pull the dumbbells up to an upright-row position, rotate the forearms until the weights point up, then press overhead.",
 "infraspinatus:3,teres minor:3,deltoid|acromial part:2,deltoid|spinal part:2,deltoid|clavicular part:2,trapezius|descending part:2,supraspinatus:2,TRI:1,serratus anterior:1,RHOMB:1"),
("Scapular push-up","Chest & shoulders","Bodyweight","In a push-up position with locked arms, sink between the shoulder blades, then push the floor away to spread them.",
 "serratus anterior:3,pectoralis minor:2,subclavius:1,RHOMB:1,trapezius|transverse part:1,pectoralis major|sternocostal part:1,TRI:1,rectus abdominis:1,transversus abdominis:1"),
("Meadows row","Back","Barbell","Stand side-on to a barbell anchored in a corner, hinge and row the end of the bar to the hip with an overhand grip.",
 "latissimus dorsi:3,trapezius|transverse part:3,deltoid|spinal part:2,RHOMB:2,teres major:2,BI:2,brachialis:2,infraspinatus:2,GRIP:1,teres minor:1,ERECT:1,OBL:1,HAMS:1,gluteus maximus:1"),
("Pendlay row","Back","Barbell","Torso parallel to the floor, bar resting on the floor each rep, pull it explosively to the lower chest.",
 "latissimus dorsi:3,trapezius|transverse part:3,RHOMB:3,deltoid|spinal part:2,teres major:2,BI:2,brachialis:2,ERECT:2,infraspinatus:1,HAMS:1,gluteus maximus:1,GRIP:1"),
("Turkish get-up","Full body","Kettlebell","Rise from lying to standing with a kettlebell held vertically overhead, then reverse every step.",
 "serratus anterior:3,external oblique:3,internal oblique:3,gluteus maximus:2,gluteus medius:2,QUADV:2,rectus abdominis:2,transversus abdominis:2,deltoid|clavicular part:2,supraspinatus:2,trapezius|descending part:2,GRIP:2,quadratus lumborum:2,TRI:1,infraspinatus:1,adductor magnus:1,HIPFLEX:1"),
("Suitcase carry","Grip & carry","Dumbbell or kettlebell","Carry one heavy weight at your side, staying tall without leaning toward it.",
 "quadratus lumborum:3,external oblique:3,internal oblique:3,GRIP:3,flexor pollicis longus:2,gluteus medius:2,trapezius|descending part:2,transversus abdominis:2,ERECT:2,multifidus:1,intertransversarii:1,levator scapulae:1,tensor fasciae latae:1,WFLEX:1,gastrocnemius:1,soleus:1"),
("Cable internal rotation","Back","Cable","Elbow pinned to the side at 90°, rotate the forearm across toward the stomach.",
 "subscapularis:3,teres major:2,latissimus dorsi:2,pectoralis major|sternocostal part:2,pectoralis major|clavicular part:1"),
("Forearm pronation and supination","Arms","Dumbbells","Forearm on the thigh, hold a hammer or one end of a dumbbell, rotate the palm down and then up.",
 "pronator teres:3,pronator quadratus:3,supinator:3,BI:2,brachioradialis:1,GRIP:1,flexor carpi radialis:1"),
("Radial deviation","Arms","Dumbbells","Forearm on the thigh, hold a dumbbell by one end with the thumb up, tilt the hand upward toward the thumb side.",
 "extensor carpi radialis longus:3,flexor carpi radialis:3,abductor pollicis longus:3,extensor pollicis brevis:3,extensor pollicis longus:2,extensor carpi radialis brevis:2,brachioradialis:1,flexor pollicis longus:1"),
("Band finger extension","Grip & carry","Resistance band","Place a band around all five fingertips and open the hand against it, then control the return.",
 "extensor digitorum:3,extensor indicis:3,extensor digiti minimi:3,extensor pollicis longus:2,extensor pollicis brevis:2,abductor pollicis longus:2,dorsal interossei (hand):2,abductor digiti minimi (hand):2,extensor carpi radialis brevis:1,extensor carpi ulnaris:1"),
("Plate pinch","Grip & carry","Weight plate","Pinch two smooth-sided plates together between thumb and fingers and hold.",
 "flexor pollicis longus:3,flexor pollicis brevis:3,adductor pollicis:3,opponens pollicis:2,abductor pollicis brevis:2,dorsal interossei (hand):2,GRIP:2,palmar interossei (hand):1,WFLEX:1"),
("Hand gripper","Grip & carry","Hand gripper","Close the gripper handles fully, hold for a moment, and open under control.",
 "GRIP:3,lumbricals (hand):3,flexor pollicis longus:2,flexor pollicis brevis:2,adductor pollicis:2,opponens pollicis:2,opponens digiti minimi (hand):2,flexor digiti minimi brevis (hand):2,palmar interossei (hand):2,WFLEX:1"),
("Banded ankle eversion","Legs","Resistance band","Seated with a band around the forefoot, turn the sole outward without moving the leg.",
 "fibularis longus:3,fibularis brevis:3,fibularis tertius:2,extensor digitorum longus:1"),
("Banded ankle inversion","Legs","Resistance band","Seated with a band around the forefoot, turn the sole inward without moving the leg.",
 "tibialis posterior:3,tibialis anterior:2,flexor digitorum longus:2,flexor hallucis longus:2,extensor hallucis longus:1"),
("Single-leg calf raise","Legs","Bodyweight","Stand on one foot on a step edge, rise high, then lower below the step for a full stretch.",
 "gastrocnemius:3,soleus:2,fibularis longus:2,fibularis brevis:2,tibialis posterior:2,flexor hallucis longus:2,flexor digitorum longus:2,plantaris:1,gluteus medius:1"),
("Short foot","Legs","Bodyweight","Barefoot, draw the ball of the big toe toward the heel without curling the toes, doming the arch.",
 "abductor hallucis:3,flexor hallucis brevis:3,flexor digitorum brevis:3,flexor accessorius:2,lumbricals (foot):2,plantar interossei (foot):2,adductor hallucis:2,abductor digiti minimi (foot):2,tibialis posterior:2,flexor digiti minimi brevis (foot):1,opponens digiti minimi (foot):1,flexor hallucis longus:1,fibularis longus:1"),
("Towel scrunch","Legs","Towel","Seated, curl the toes to pull a towel under the foot, then smooth it out and repeat.",
 "flexor digitorum longus:3,flexor digitorum brevis:3,flexor hallucis longus:3,flexor hallucis brevis:2,flexor accessorius:2,lumbricals (foot):2,plantar interossei (foot):2,adductor hallucis:2,flexor digiti minimi brevis (foot):1,tibialis posterior:1"),
("Seated hip external rotation","Legs","Resistance band","Seated with a band anchored on the outside of the foot, keep the knee still and sweep the foot inward.",
 "piriformis:3,obturator internus:3,obturator externus:3,gemellus superior:3,gemellus inferior:3,quadratus femoris:3,gluteus maximus:2,gluteus medius:1,sartorius:1"),
("Cossack squat","Legs","Bodyweight","In a wide stance, shift side to side and squat deep over one leg while the other stays straight with the toes up.",
 "adductor magnus:3,adductor longus:3,gracilis:3,QUADV:3,gluteus maximus:3,adductor brevis:2,pectineus:2,sartorius:2,HAMS:1,gluteus medius:1,soleus:1"),
("Standing cable hip flexion","Legs","Cable","Ankle strap on the working leg, face away from the stack and drive the knee forward and up.",
 "HIPFLEX:3,rectus femoris:3,sartorius:2,tensor fasciae latae:2,pectineus:2,adductor longus:1,rectus abdominis:1,OBL:1"),
("Neck lateral flexion","Neck","Resistance band","Band anchored at head height, side-bend the head against it while the shoulders stay still.",
 "sternocleidomastoid:3,scalenus medius:3,scalenus posterior:3,scalenus anterior:2,levator scapulae:2,splenius cervicis:2,splenius capitis:2,rectus capitis lateralis:2,trapezius|descending part:2,semispinalis:1,iliocostalis|iliocostalis cervicis:1,longissimus|longissimus cervicis:1"),
("Chin tuck","Neck","Bodyweight","Glide the chin straight back without tilting the head, hold briefly, release.",
 "longus colli:3,longus capitis:3,rectus capitis anterior:3,scalenus anterior:1,sternocleidomastoid:1"),
("Prone head lift","Neck","Bodyweight","Face down with the forehead just off the floor, nod the chin up and lift the head, then lower with control.",
 "splenius capitis:3,semispinalis:3,rectus capitis posterior major:3,rectus capitis posterior minor:3,splenius cervicis:2,longissimus|longissimus capitis:2,trapezius|descending part:1,levator scapulae:1"),
("Dumbbell side bend","Core","Dumbbells","Stand tall holding a dumbbell at one side, bend sideways and return without twisting.",
 "quadratus lumborum:3,internal oblique:3,external oblique:3,intertransversarii:2,iliocostalis|iliocostalis lumborum:2,multifidus:1,rectus abdominis:1,transversus abdominis:1,GRIP:1,gluteus medius:1"),
("Rotary torso machine","Core","Machine","Seated with the pelvis fixed, rotate the torso against the pad, turning from the ribs.",
 "external oblique:3,internal oblique:3,rotatores:2,multifidus:2,transversus abdominis:1,rectus abdominis:1"),
("Diaphragmatic breathing","Core","Bodyweight","Lying with the knees bent, inhale slowly into the belly and lower ribs, then exhale fully and draw the ribs down.",
 "diaphragm:3,external intercostal:2,internal intercostal:2,innermost intercostal:2,levatores costarum:2,transversus thoracis:2,transversus abdominis:2,scalenus anterior:1,levator ani:1,rectus abdominis:1,serratus posterior inferior:1,serratus posterior superior:1,subclavius:1"),
("Pelvic floor contraction","Core","Bodyweight","Lying or seated, gently draw the pelvic floor up and in, hold for a few seconds without clenching the glutes.",
 "levator ani:3,coccygeus:3,external anal sphincter:3,transversus abdominis:2,obturator internus:2,multifidus:1"),
]
out=[]
for name,cat,eq,cue,spec in E:
    t={}
    for item in spec.split(','):
        k,l=item.rsplit(':',1); l=int(l)
        ks=G.get(k,[k])
        for kk in ks:
            key,_,part=kk.partition('|')
            assert key in DB,(name,key)
            if part: assert part in parts.get(key,set()),(name,key,part,parts.get(key))
            t[(key,part)]=max(t.get((key,part),0),l)
    out.append({'n':name,'c':cat,'e':eq,'q':cue,'t':[[k,p,l] for (k,p),l in sorted(t.items(),key=lambda x:-x[1])]})
M['ex']=out
json.dump(M,open('meta3.json','w',encoding='utf-8',newline='\n'),separators=(',',':'))
print(len(out),'exercises; muscles covered',len({k for e in out for k,_,_ in e['t']}))

# ---------- variations: override levels (0 removes) ----------
VARS={
"Barbell bench press":[("Grip",[("Standard",""),("Wide","pectoralis major|sternocostal part:3,pectoralis major|clavicular part:2,TRI:1"),("Close","TRI:3,pectoralis major|sternocostal part:2")])],
"Push-up":[("Hands",[("Standard",""),("Wide","pectoralis major|sternocostal part:3,TRI:1"),("Close","TRI:3,pectoralis major|sternocostal part:2")]),
           ("Feet",[("Floor",""),("Elevated","pectoralis major|clavicular part:3,deltoid|clavicular part:3,pectoralis major|sternocostal part:2")])],
"Dips":[("Torso",[("Forward lean",""),("Upright","TRI:3,pectoralis major|sternocostal part:2,pectoralis major|abdominal part:2")])],
"Pull-up":[("Grip",[("Overhand",""),("Wide overhand","latissimus dorsi:3,teres major:3,BI:1,brachialis:1"),("Neutral","brachialis:3,brachioradialis:3,BI:2")])],
"Lat pulldown":[("Grip",[("Wide overhand",""),("Close neutral","RHOMB:2,brachialis:3,brachioradialis:2,trapezius|transverse part:1"),("Underhand","BI:3,pectoralis major|sternocostal part:1")])],
"Seated cable row":[("Elbows",[("Tucked","latissimus dorsi:3,trapezius|transverse part:2,deltoid|spinal part:1"),("Flared","trapezius|transverse part:3,deltoid|spinal part:3,latissimus dorsi:2,infraspinatus:1")])],
"Barbell row":[("Grip",[("Overhand",""),("Underhand","BI:3,latissimus dorsi:3,trapezius|transverse part:2,deltoid|spinal part:1")])],
"Barbell curl":[("Grip",[("Shoulder-width",""),("Wide","biceps brachii|short head:3,biceps brachii|long head:2"),("Close","biceps brachii|long head:3,biceps brachii|short head:2"),("Reverse (overhand)","brachioradialis:3,brachialis:3,BI:1,extensor carpi radialis longus:2,extensor carpi radialis brevis:1")])],
"Back squat":[("Stance",[("Shoulder-width",""),("Wide","adductor magnus:3,adductor longus:2,gluteus maximus:3"),("Narrow","QUADV:3,adductor magnus:1,gluteus maximus:2")]),
              ("Depth",[("Parallel",""),("Deep","gluteus maximus:3,adductor magnus:3"),("Half","gluteus maximus:2,adductor magnus:1")])],
"Leg press":[("Feet",[("Middle",""),("High","gluteus maximus:3,HAMS:2,QUADV:2,adductor magnus:2"),("Low","QUADV:3,gluteus maximus:1"),("Wide","adductor magnus:3,adductor longus:2,gluteus maximus:2")])],
"Bulgarian split squat":[("Torso",[("Upright","QUADV:3,gluteus maximus:2"),("Forward lean","gluteus maximus:3,HAMS:2,QUADV:2")])],
"Hip thrust":[("Feet",[("Standard",""),("Far from hips","HAMS:2,QUADV:0"),("Close to hips","QUADV:2,HAMS:0")])],
"Romanian deadlift":[("Knees",[("Soft bend",""),("Straight (stiff-leg)","HAMS:3,gluteus maximus:2,ERECT:3")])],
"Lateral raise":[("Arm path",[("Out to the side",""),("In the scapular plane","deltoid|acromial part:3,deltoid|clavicular part:2,supraspinatus:2")])],
"Side-lying hip abduction":[("Leg position",[("Slightly behind, toes forward",""),("Forward, toes up","tensor fasciae latae:3,gluteus medius:2,iliacus:1,rectus femoris:1,sartorius:1")])],
"Standing cable hip abduction":[("Hip position",[("Neutral or slightly extended",""),("Slightly flexed, toes in","tensor fasciae latae:3,gluteus minimus:3,gluteus medius:2,iliacus:1,rectus femoris:1")])],
"Hip abduction machine":[("Torso",[("Upright",""),("Leaning forward","gluteus maximus:3,gluteus medius:3,tensor fasciae latae:2,piriformis:2")])],
"Single-leg calf raise":[("Knee",[("Straight",""),("Bent","soleus:3,gastrocnemius:1,plantaris:0")])],
"Forearm pronation and supination":[("Direction",[("Both",""),("Pronation only","pronator teres:3,pronator quadratus:3,supinator:0,BI:0"),("Supination only","supinator:3,BI:3,pronator teres:0,pronator quadratus:0")])],
"Pendlay row":[("Grip",[("Overhand",""),("Underhand","BI:3,latissimus dorsi:3,trapezius|transverse part:2,deltoid|spinal part:1")])],
"Standing cable hip flexion":[("Knee",[("Straight leg","rectus femoris:3,tensor fasciae latae:3,HIPFLEX:2"),("Bent knee","HIPFLEX:3,rectus femoris:2,sartorius:3,tensor fasciae latae:1")])],
"Prone Y-T-W raise":[("Shape",[("Y",""),("T","trapezius|ascending part:1,trapezius|transverse part:3,RHOMB:3,deltoid|spinal part:3,deltoid|acromial part:2"),("W","infraspinatus:3,teres minor:3,RHOMB:3,trapezius|ascending part:2,trapezius|transverse part:2,deltoid|spinal part:2,deltoid|acromial part:0,supraspinatus:0")])],
"Standing calf raise":[("Feet",[("Straight",""),("Toes out","gastrocnemius|medial head:3,gastrocnemius|lateral head:2"),("Toes in","gastrocnemius|lateral head:3,gastrocnemius|medial head:2")])],
}
idx={e['n']:e for e in out}
def expand(spec):
    res=[]
    if not spec: return res
    for item in spec.split(','):
        k,l=item.rsplit(':',1); l=int(l)
        for kk in G.get(k,[k]):
            key,_,part=kk.partition('|'); assert key in DB,key
            if part: assert part in parts.get(key,set()),(key,part)
            res.append([key,part,l])
    return res
for n,groups in VARS.items():
    assert n in idx,n
    idx[n]['v']=[[g,[[o,expand(s)] for o,s in opts]] for g,opts in groups]
# equipment categories
EQ={"Barbell":["Barbell"],"Trap bar":["Barbell"],"Dumbbells":["Dumbbells"],"Dumbbell or kettlebell":["Dumbbells","Kettlebell"],"Kettlebell":["Kettlebell"],
    "Cable":["Cable"],"Cable or dumbbell":["Cable","Dumbbells"],"Machine":["Machine"],"Bodyweight":["Bodyweight"],"Parallel bars":["Bodyweight"],
    "Bar":["Bodyweight"],"Bench":["Bodyweight"],"Resistance band":["Band"],"Weight plate":["Other"],"Neck harness":["Other"],"Ab wheel":["Other"],"Wrist roller":["Other"],"Hand gripper":["Other"],"Towel":["Other"]}
for e in out: e['eq']=EQ[e['e']]
M['ex']=out
json.dump(M,open('meta3.json','w',encoding='utf-8',newline='\n'),separators=(',',':'))
print('variations on',len(VARS))
